---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Honors Baccalaureate", "2019", "Montana State University", "Bozeman, Montana",
  "Bachelor of Arts, Political Science", "2019", "Montana State University", "Bozeman, Montana",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Honors

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2019, "Marshall Scholarship", "National Finalist",
  2020, "Goetz Award", "Awarded for Excellence in Political Science"
  2018, "Hansard Society Fellow"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
scholar::get_publications("EmD_lTEAAAAJ&EmD_lTEAAAAJ&") %>% 
  filter(cites > 30) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("curie.bib")

bibliography_entries("curie.bib")
```

